### ISSUE TITLE
Check/remove unexpected images

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/hg-novice#28]
`make lesson-check` reports:

Unexpected image files: bitbucket-find-repo-string.png, hg-after-change-to-duplicate-repo.svg, hg-after-duplicate-clone.svg, hg-after-first-conflicting-change.svg, hg-after-merging.svg, hg-after-pulling-to-local-repo.svg, hg-after-second-conflicting-change.svg, hg-freshly-made-bitbucket-repo.svg, hg-kdiff3-conflict-windows-resolved.png, hg-kdiff3-conflict-windows.png

**Comment by douglatornell** [comment]
At a glance those look like the expected image files for the lesson, so I guess I need to figure out how to make `lesson-check` aware of them.

I was hoping to work on the lesson this week, but the last 2 days have been completely consumed getting [this client project](https://resilient-c.ubc.ca/) ready for release.
